{% set name = "fsspec-xrootd" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fsspec_xrootd-{{ version }}.tar.gz
  sha256: 3a146f9c0784d21b5b269981cd394d3d521e273d50dbd71b8315d70bd6078ddd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - fsspec
    - xrootd

test:
  imports:
    - fsspec_xrootd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CoffeaTeam/fsspec-xrootd
  summary: xrootd implementation for fsspec
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - nsmith-
    - lobis
